### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by anjum121** [iata-ndc/ndc-js-sdk#8]
I was getting below error when following Readme doc and try to run application.

`Error: Cannot find module 'debug'`

Please add below code in your Readme file 

`npm install debug --save-dev`

which fixed my node error

**Comment by CDixonIATA** [comment]
Hi Adjum,

Thanks for the feedback, I have updated the readme to reflect this dependency for people who do not already have the module to know that they need to install it.

Best regards,
Chris
